config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :people do
    resources :animals
  end

  resources :animal_types

  root to: 'home#index'
end

app/controllers/animal_types_controller.rb
# frozen_string_literal: true

class AnimalTypesController < ApplicationController
  before_action :set_animal_type, only: %i[show edit update destroy]

  # GET /animal_types
  # GET /animal_types.json
  def index
    @animal_types = AnimalType.all
  end

  # GET /animal_types/1
  # GET /animal_types/1.json
  def show; end

  # GET /animal_types/new
  def new
    @animal_type = AnimalType.new
  end

  # GET /animal_types/1/edit
  def edit; end

  # POST /animal_types
  # POST /animal_types.json
  def create
    @animal_type = AnimalType.new(animal_type_params)

    respond_to do |format|
      if @animal_type.save
        format.html { redirect(@animal_type, :create, 'animal_type') }
        format.json { render :show, status: :created, location: @animal_type }
      else
        format.html { render :new }
        format.json { render_json(@animal_type.errors, :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /animal_types/1
  # PATCH/PUT /animal_types/1.json
  def update
    respond_to do |format|
      if @animal_type.update(animal_type_params)
        format.html { redirect(@animal_type, :update, 'animal_type') }
        format.json { render :show, status: :ok, location: @animal_type }
      else
        format.html { render :edit }
        format.json { render_json(@animal_type.errors, :unprocessable_entity) }
      end
    end
  end

  # DELETE /animal_types/1
  # DELETE /animal_types/1.json
  def destroy
    @animal_type.destroy
    respond_to do |format|
      format.html { redirect(animal_types_url, :delete, 'animal_type') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_animal_type
    @animal_type = AnimalType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def animal_type_params
    params.require(:animal_type).permit(:name)
  end
end

app/views/animal_types/_form.html.erb
<%= form_with(model: animal_type, local: true) do |form| %>
  <% if animal_type.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(animal_type.errors.count, "erro(s)") %>
        <%= t('activerecord.models.errors.errors_message',
          model: t('activerecord.attributes.animal_type.name')) %>:
      </h2>

      <ul>
      <% animal_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animal_types/edit.html.erb
<h1>
  <%= t(:editing, model: t('activerecord.models.animal_type.one')) %>
</h1>

<%= render 'form', animal_type: @animal_type %>

<%= link_to t(:show), @animal_type %> |
<%= link_to t(:back), animal_types_path %>

app/views/animal_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.animal_type.other') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.animal_type.name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animal_types.each do |animal_type| %>
      <tr>
        <td><%= animal_type.name %></td>
        <td><%= link_to t(:show), animal_type %></td>
        <td>
          <%= link_to t(:edit), edit_animal_type_path(animal_type) %>
        </td>
        <td>
          <%= link_to t(:destroy), animal_type,
            method: :delete, data: { confirm: t(:confirm) }%>    
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
<%= link_to t(:new, model: t('activerecord.models.animal_type.one')),
  new_animal_type_path %>
</div>

<div>
  <%= link_to t(:back), home_index_path %>
</div>

app/views/animal_types/new.html.erb
<h1><%= t(:new, model: t('activerecord.models.animal_type.other')) %></h1>

<%= render 'form', animal_type: @animal_type %>

<%= link_to t(:back), animal_types_path %>

app/views/animal_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.animal_type.name') %>:</strong>
  <%= @animal_type.name %>
</p>

<%= link_to t(:edit), edit_animal_type_path(@animal_type) %> |
<%= link_to t(:back), animal_types_path %>