config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :people do
    resources :animals
  end

  resources :animal_types

  root to: 'home#index'
end

app/models/person.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: people
#
#  id           :bigint           not null, primary key
#  name         :string
#  paper_number :string
#  birth_date   :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Person < ApplicationRecord
  has_many :animals

  validates_presence_of :name, :paper_number, :birth_date

  def initial_letter
    name[0]
  end

  def total_monthly_cost
    animals.map(&:monthly_cost).sum
  end

  def over_monthly_cost?
    total_monthly_cost > ENV['MAX_TOTAL_ANIMAL_COST'].to_i
  end

  def age
    ((Time.now - birth_date.to_time) / 1.year.seconds).floor
  end

  def not_allowed_by_initial?(animal_type)
    not_allowed_initials = ENV['NOT_ALLOWED_INITIALS'].to_s.split(',')
    not_allowed_animal_types = ENV['ANIMAL_TYPES_NOT_ALLOWED_BY_INITIAL']
      .to_s.split(',')

    if not_allowed_initials.include?(initial_letter) &&
        not_allowed_animal_types.include?(animal_type)
      return true
    end

    false
  end

  def not_allowed_by_age?(animal_type)
    minimum_age = ENV['MINIMUM_AGE'].to_i

    not_allowed_animal_types = ENV[
      'ANIMAL_TYPES_NOT_ALLOWED_BELLOW_MINIMUM_AGE'
    ].to_s.split(',')

    return true if age < minimum_age && not_allowed_animal_types
      .include?(animal_type)

    false
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect(@person, :create, 'person') }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render_json(@person.errors, :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect(@person, :update, 'person') }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render_json(@person.errors, :unprocessable_entity) }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect(people_url, :delete, 'person') }

      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:name, :paper_number, :birth_date)
  end
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(person.errors.count, "erro(s)") %>
        <%= t('activerecord.errors.errors_message',
          model: t('activerecord.attributes.person.name')) %>:
      </h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :paper_number %>
    <%= form.text_field :paper_number %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1><%= t(:editing, model: t("activerecord.models.person.one")) %></h1>

<%= render 'form', person: @person %>

<%= link_to t(:show), @person %> |
<%= link_to t(:back), people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.person.other') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.person.name') %></th>
      <th><%= t('activerecord.attributes.person.paper_number') %></th>
      <th><%= t('activerecord.attributes.person.birth_date') %></th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.paper_number %></td>
        <td><%= l(person.birth_date) %></td>
        <th><%= link_to t('people.animals'), person_animals_path(person) %></th>
        <td><%= link_to t(:show), person %></td>
        <td><%= link_to t(:edit), edit_person_path(person) %></td>
        <td><%= link_to t(:edit), edit_person_path(person) %></td>
        <td>
          <%= link_to t(:destroy), person,
            method: :delete, data: { confirm: t(:confirm) } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= link_to t(:new, model: t('activerecord.models.person.one')),
    new_person_path %>
</div>

<div>
  <%= link_to t(:back), home_index_path %>
</div>

app/views/people/new.html.erb
<h1><%= t(:new, model: t("activerecord.models.person.one")) %></h1>

<%= render 'form', person: @person %>

<%= link_to t(:back), people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.person.name') %>:</strong>
  <%= @person.name %>
</p>

<p>
  <strong><%= t('activerecord.attributes.person.paper_number') %>:</strong>
  <%= @person.paper_number %>
</p>

<p>
  <strong><%= t('activerecord.attributes.person.birth_date') %>:</strong>
  <%= l(@person.birth_date) %>
</p>

<%= link_to t(:edit), edit_person_path(@person) %> |
<%= link_to t(:back), people_path %>