config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :people do
    resources :animals
  end

  resources :animal_types

  root to: 'home#index'
end

app/models/animal.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: animals
#
#  id             :bigint           not null, primary key
#  name           :string
#  monthly_cost   :decimal(10, 2)
#  person_id      :bigint
#  animal_type_id :bigint
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Animal < ApplicationRecord
  belongs_to :person
  belongs_to :animal_type

  validates_presence_of :name
  validates :monthly_cost, presence: true,
                           numericality: { greater_than: 0 }

  validates_with AnimalValidator

  def monthly_cost=(param)
    return unless param

    self[:monthly_cost] = if param.is_a?(Numeric)
                            param
                          else
                            param.gsub(',', '.')
                          end
  end
end

app/models/animal_type.rb
# frozen_string_literal: true

class AnimalType < ApplicationRecord
  has_many :animals
end

app/controllers/animals_controller.rb
# frozen_string_literal: true

class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[show edit update destroy]
  before_action :set_person

  # GET /animals
  # GET /animals.json
  def index
    @animals = @person.animals
  end

  # GET /animals/1
  # GET /animals/1.json
  def show; end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit; end

  # POST /animals
  # POST /animals.json
  # rubocop:disable Metrics/MethodLength
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html do
          redirect(person_animal_url(@person, @animal), :create, 'animal')
        end

        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render_json(@animal.errors, :unprocessable_entity) }
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  # rubocop:disable Metrics/MethodLength
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html do
          redirect(person_animal_url(@person, @animal), :update, 'animal')
        end

        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render_json(animal.errors, :unprocessable_entity) }
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect(person_animals_url, :delete, 'animal') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:person_id])
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def animal_params
    params.require(:animal)
      .permit(:name, :monthly_cost, :person_id, :animal_type_id)
  end
end

app/views/animals/_form.html.erb
<%= form_with(model: [@person, animal], local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(animal.errors.count, "erro(s)") %>
        <%= t('activerecord.errors.errors_message',
          model: t('activerecord.attributes.animal.name')) %>:
      </h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :monthly_cost %>
    <%= form.text_field :monthly_cost %>
  </div>

  <div class="field">
    <%= form.label :animal_type_id %>
    <%= form.select :animal_type_id,
        AnimalType.all.collect { |animal| [animal.name, animal.id] } %>
  </div>

  <%= form.hidden_field :person_id, value: @person.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1><%= t(:editing, model: t('activerecord.models.animal.one')) %></h1>

<%= render 'form', animal: @animal %>

<%= link_to t(:show), person_animal_path(@person, @animal) %> |
<%= link_to t(:back), person_animals_path(@person) %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.animal.other') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.animal.name') %></th>
      <th><%= t('activerecord.attributes.animal.monthly_cost') %></th>
      <th><%= t('activerecord.attributes.animal.person') %></th>
      <th><%= t('activerecord.attributes.animal.animal_type') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.monthly_cost %></td>
        <td><%= animal.person.name %></td>
        <td><%= animal.animal_type.name %></td>
        <td><%= link_to t(:show), person_animal_path(@person.id, animal) %></td>
        <td>
          <%= link_to t(:edit), edit_person_animal_path(@person.id, animal) %>
        </td>
        <td>
          <%= link_to t(:destroy), person_animal_path(@person.id, animal),
            method: :delete, data: { confirm: t(:confirm) } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= link_to t(:new, model: t('activerecord.models.animal.one')),
    new_person_animal_path(@person) %>
</div>

<div>
  <%= link_to t(:back), people_path %>
</div>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to t(:back), person_animals_path(@person) %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.animal.name') %>:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong><%= t('activerecord.attributes.animal.monthly_cost') %>:</strong>
  <%= @animal.monthly_cost %>
</p>

<p>
  <strong><%= t('activerecord.attributes.animal.person') %>:</strong>
  <%= @animal.person.name %>
</p>

<p>
  <strong><%= t('activerecord.attributes.animal.animal_type') %>:</strong>
  <%= @animal.animal_type.name %>
</p>

<%= link_to t(:edit), edit_person_animal_path(@person, @animal) %> |
<%= link_to t(:back), person_animals_path(@person) %>